// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd9mL-HieHDAqyeIqSnpqnf7NCCXoXJ84',
    appId: '1:415411570292:web:81034b4bc08128a86e3321',
    messagingSenderId: '415411570292',
    projectId: 'cashbook-8aebd',
    authDomain: 'cashbook-8aebd.firebaseapp.com',
    storageBucket: 'cashbook-8aebd.firebasestorage.app',
    measurementId: 'G-T81VBYZCQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGqegDsWzzZrgWQ6uR0DfvHRv_nIlkw4c',
    appId: '1:415411570292:android:2b526569d778ce426e3321',
    messagingSenderId: '415411570292',
    projectId: 'cashbook-8aebd',
    storageBucket: 'cashbook-8aebd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-ifdlEFZAwnOmNNpqpX7Tb2iGEI41h6w',
    appId: '1:415411570292:ios:50c642e68f0d8ec46e3321',
    messagingSenderId: '415411570292',
    projectId: 'cashbook-8aebd',
    storageBucket: 'cashbook-8aebd.firebasestorage.app',
    iosBundleId: 'com.example.cashbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-ifdlEFZAwnOmNNpqpX7Tb2iGEI41h6w',
    appId: '1:415411570292:ios:50c642e68f0d8ec46e3321',
    messagingSenderId: '415411570292',
    projectId: 'cashbook-8aebd',
    storageBucket: 'cashbook-8aebd.firebasestorage.app',
    iosBundleId: 'com.example.cashbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd9mL-HieHDAqyeIqSnpqnf7NCCXoXJ84',
    appId: '1:415411570292:web:2450d0e64ad2eace6e3321',
    messagingSenderId: '415411570292',
    projectId: 'cashbook-8aebd',
    authDomain: 'cashbook-8aebd.firebaseapp.com',
    storageBucket: 'cashbook-8aebd.firebasestorage.app',
    measurementId: 'G-X7H71C2PT3',
  );

}